In [1]:
import numpy as np

In [4]:
n = int(input("Enter the order of the square matrix (n x n): "))
print(f"Enter the {n*n} elements row-wise:")

Enter the order of the square matrix (n x n):  3


Enter the 9 elements row-wise:


In [5]:
elements = []
for i in range(n):
    row = list(map(int, input(f"Row {i+1}: ").split()))
    while len(row) != n:
        print(f"Please enter exactly {n} elements.")
        row = list(map(int, input(f"Row {i+1}: ").split()))
    elements.append(row)

Row 1:  1 2 3
Row 2:  4 5 6
Row 3:  7 8 9


In [6]:
matrix = np.array(elements)

In [7]:
diagonal_sum = 0
for i in range(n):
    diagonal_sum += matrix[i][i]


In [8]:
print("Matrix:")
print(matrix)
print("Sum of diagonal elements:", diagonal_sum)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of diagonal elements: 15
